#!/usr/bin/env python3
"""
Simple and robust web files embedding for ESP32.
This version splits large files into chunks and uses a more reliable encoding.
"""

import os
import sys
from pathlib import Path

# Configuration
UPLOAD_DIR = "upload"
OUTPUT_DIR = "src/generated"
MAX_CHUNK_SIZE = 8192  # 8KB chunks for reliable transmission

def safe_name(filename):
    """Convert filename to safe C identifier."""
    return filename.replace('.', '_').replace('-', '_').replace('/', '_')

def file_to_chunks(file_path):
    """Split a file into chunks and create C arrays for each chunk."""
    file_name = file_path.name
    safe_file_name = safe_name(file_name)
    
    # Read file content
    with open(file_path, 'rb') as f:
        content = f.read()
    
    file_size = len(content)
    chunks = []
    
    # Split into chunks
    for i in range(0, file_size, MAX_CHUNK_SIZE):
        chunk = content[i:i + MAX_CHUNK_SIZE]
        chunks.append(chunk)
    
    return chunks, file_size

def create_chunked_header(file_path, output_dir):
    """Create a header file with chunked data."""
    file_name = file_path.name
    safe_file_name = safe_name(file_name)
    header_name = f"chunked_{safe_file_name}"
    output_path = output_dir / f"{header_name}.h"
    
    chunks, file_size = file_to_chunks(file_path)
    
    # Determine content type
    content_type = get_content_type(file_name)
    
    print(f"Creating chunked header for {file_name} ({file_size} bytes, {len(chunks)} chunks)")
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(f"// Auto-generated chunked file: {file_name}\n")
        f.write(f"// Generated by embed_webfiles_simple.py - DO NOT MODIFY MANUALLY\n")
        f.write(f"// Content-Type: {content_type}\n")
        f.write(f"// File size: {file_size} bytes\n")
        f.write(f"// Number of chunks: {len(chunks)}\n\n")
        
        f.write(f"#ifndef {header_name.upper()}_H\n")
        f.write(f"#define {header_name.upper()}_H\n\n")
        f.write(f"#include <Arduino.h>\n\n")
        
        # Write each chunk
        for i, chunk in enumerate(chunks):
            f.write(f"// Chunk {i + 1}/{len(chunks)} ({len(chunk)} bytes)\n")
            f.write(f"const uint8_t {safe_file_name}_chunk_{i}[] PROGMEM = {{\n")
            
            # Write bytes in rows of 16
            for j in range(0, len(chunk), 16):
                row = chunk[j:j + 16]
                hex_values = [f"0x{byte:02X}" for byte in row]
                f.write(f"    {', '.join(hex_values)}")
                if j + 16 < len(chunk):
                    f.write(",")
                f.write("\n")
            
            f.write(f"}};\n")
            f.write(f"const size_t {safe_file_name}_chunk_{i}_size = {len(chunk)};\n\n")
        
        # Create chunk array
        f.write(f"// Array of chunk pointers\n")
        f.write(f"const uint8_t* {safe_file_name}_chunks[] = {{\n")
        for i in range(len(chunks)):
            f.write(f"    {safe_file_name}_chunk_{i}")
            if i < len(chunks) - 1:
                f.write(",")
            f.write("\n")
        f.write(f"}};\n\n")
        
        # Create chunk sizes array
        f.write(f"const size_t {safe_file_name}_chunk_sizes[] = {{\n")
        for i in range(len(chunks)):
            f.write(f"    {safe_file_name}_chunk_{i}_size")
            if i < len(chunks) - 1:
                f.write(",")
            f.write("\n")
        f.write(f"}};\n\n")
        
        # File metadata
        f.write(f"const size_t {safe_file_name}_total_size = {file_size};\n")
        f.write(f"const size_t {safe_file_name}_num_chunks = {len(chunks)};\n")
        f.write(f"const char {safe_file_name}_content_type[] = \"{content_type}\";\n")
        f.write(f"const char {safe_file_name}_filename[] = \"{file_name}\";\n")
        
        f.write(f"\n#endif // {header_name.upper()}_H\n")
    
    return {
        'filename': file_name,
        'safe_name': safe_file_name,
        'content_type': content_type,
        'size': file_size,
        'num_chunks': len(chunks)
    }

def get_content_type(filename):
    """Get content type based on file extension."""
    ext = filename.lower().split('.')[-1]
    types = {
        'html': 'text/html',
        'css': 'text/css',
        'js': 'application/javascript',
        'json': 'application/json',
        'txt': 'text/plain',
        'jpg': 'image/jpeg',
        'jpeg': 'image/jpeg',
        'png': 'image/png',
        'gif': 'image/gif',
        'svg': 'image/svg+xml',
        'ico': 'image/x-icon',
        'md': 'text/markdown'
    }
    return types.get(ext, 'application/octet-stream')

def create_chunked_registry(files_info, output_dir):
    """Create a registry for all chunked files."""
    registry_h = output_dir / "chunked_files_registry.h"
    registry_cpp = output_dir / "chunked_files_registry.cpp"
    
    with open(registry_h, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated chunked files registry\n")
        f.write("// Generated by embed_webfiles_simple.py - DO NOT MODIFY MANUALLY\n\n")
        f.write("#ifndef CHUNKED_FILES_REGISTRY_H\n")
        f.write("#define CHUNKED_FILES_REGISTRY_H\n\n")
        f.write("#include <Arduino.h>\n\n")
        
        # Include all chunk headers
        for info in files_info:
            f.write(f"#include \"chunked_{info['safe_name']}.h\"\n")
        f.write("\n")
        
        # Structure definition
        f.write("struct ChunkedFile {\n")
        f.write("    const char* filename;\n")
        f.write("    const char* content_type;\n")
        f.write("    const uint8_t** chunks;\n")
        f.write("    const size_t* chunk_sizes;\n")
        f.write("    size_t num_chunks;\n")
        f.write("    size_t total_size;\n")
        f.write("};\n\n")
        
        f.write("extern const ChunkedFile chunked_files[];\n")
        f.write("extern const size_t chunked_files_count;\n\n")
        f.write("const ChunkedFile* findChunkedFile(const char* path);\n")
        f.write("bool serveChunkedFile(WiFiClient client, const char* path);\n\n")
        f.write("#endif // CHUNKED_FILES_REGISTRY_H\n")
    
    with open(registry_cpp, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated chunked files registry implementation\n")
        f.write("// Generated by embed_webfiles_simple.py - DO NOT MODIFY MANUALLY\n\n")
        f.write("#include \"chunked_files_registry.h\"\n")
        f.write("#include <string.h>\n")
        f.write("#include <WiFi.h>\n\n")
        
        # Registry array
        f.write("const ChunkedFile chunked_files[] = {\n")
        for i, info in enumerate(files_info):
            f.write("    {\n")
            f.write(f"        {info['safe_name']}_filename,\n")
            f.write(f"        {info['safe_name']}_content_type,\n")
            f.write(f"        {info['safe_name']}_chunks,\n")
            f.write(f"        {info['safe_name']}_chunk_sizes,\n")
            f.write(f"        {info['safe_name']}_num_chunks,\n")
            f.write(f"        {info['safe_name']}_total_size\n")
            f.write("    }")
            if i < len(files_info) - 1:
                f.write(",")
            f.write("\n")
        f.write("};\n\n")
        
        f.write(f"const size_t chunked_files_count = {len(files_info)};\n\n")
        
        # Find function
        f.write("const ChunkedFile* findChunkedFile(const char* path) {\n")
        f.write("    // Remove leading slash if present\n")
        f.write("    if (path[0] == '/') {\n")
        f.write("        path++;\n")
        f.write("    }\n")
        f.write("    \n")
        f.write("    for (size_t i = 0; i < chunked_files_count; i++) {\n")
        f.write("        if (strcmp(chunked_files[i].filename, path) == 0) {\n")
        f.write("            return &chunked_files[i];\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write("    \n")
        f.write("    return nullptr;\n")
        f.write("}\n\n")
        
        # Serve function
        f.write("bool serveChunkedFile(WiFiClient client, const char* path) {\n")
        f.write("    const ChunkedFile* file = findChunkedFile(path);\n")
        f.write("    \n")
        f.write("    if (file == nullptr) {\n")
        f.write("        return false;\n")
        f.write("    }\n")
        f.write("    \n")
        f.write("    // Send HTTP header\n")
        f.write("    client.println(\"HTTP/1.1 200 OK\");\n")
        f.write("    client.print(\"Content-Type: \");\n")
        f.write("    client.println(file->content_type);\n")
        f.write("    client.print(\"Content-Length: \");\n")
        f.write("    client.println(file->total_size);\n")
        f.write("    client.println(\"Connection: close\");\n")
        f.write("    client.println(\"Cache-Control: no-cache, no-store, must-revalidate\");\n")
        f.write("    client.println(\"Pragma: no-cache\");\n")
        f.write("    client.println();\n")
        f.write("    \n")
        f.write("    // Send file content chunk by chunk\n")
        f.write("    for (size_t i = 0; i < file->num_chunks; i++) {\n")
        f.write("        // Read chunk from PROGMEM\n")
        f.write("        uint8_t buffer[8192];\n")
        f.write("        size_t chunk_size = file->chunk_sizes[i];\n")
        f.write("        memcpy_P(buffer, file->chunks[i], chunk_size);\n")
        f.write("        \n")
        f.write("        // Send chunk\n")
        f.write("        client.write(buffer, chunk_size);\n")
        f.write("        \n")
        f.write("        // Small delay for reliability\n")
        f.write("        if (i < file->num_chunks - 1) {\n")
        f.write("            yield();\n")
        f.write("            delay(1);\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write("    \n")
        f.write("    return true;\n")
        f.write("}\n")

def main():
    """Main function."""
    upload_dir = Path(UPLOAD_DIR)
    output_dir = Path(OUTPUT_DIR)
    
    if not upload_dir.exists():
        print(f"Error: Upload directory '{UPLOAD_DIR}' does not exist!")
        return 1
    
    # Create output directory
    output_dir.mkdir(exist_ok=True)
    
    print("Starting simple chunked web files embedding...")
    print(f"Input directory: {upload_dir}")
    print(f"Output directory: {output_dir}")
    
    files_info = []
    
    # Process all files
    for file_path in upload_dir.rglob('*'):
        if file_path.is_file():
            info = create_chunked_header(file_path, output_dir)
            files_info.append(info)
    
    # Create registry
    create_chunked_registry(files_info, output_dir)
    
    print(f"\nEmbedding complete!")
    print(f"Files embedded: {len(files_info)}")
    total_size = sum(info['size'] for info in files_info)
    print(f"Total size: {total_size:,} bytes ({total_size/1024:.1f} KB)")
    
    return 0

if __name__ == "__main__":
    sys.exit(main()) 