#!/usr/bin/env python3
"""
Embed Web Files Script for DPV Control Project

This script converts all files from the 'upload' directory into embedded C++ header files.
It runs before compilation to ensure all web files are embedded directly in the firmware,
eliminating the need for SPIFFS/LittleFS file uploads that would overwrite persistent data.

Generated files are placed in src/generated/ and should be in .gitignore.
"""

import os
import sys
import base64
import hashlib
from pathlib import Path

def get_content_type(filename):
    """Return the appropriate content type for a file extension."""
    ext = Path(filename).suffix.lower()
    content_types = {
        '.html': 'text/html',
        '.css': 'text/css',
        '.js': 'application/javascript',
        '.json': 'application/json',
        '.png': 'image/png',
        '.jpg': 'image/jpeg',
        '.jpeg': 'image/jpeg',
        '.gif': 'image/gif',
        '.ico': 'image/x-icon',
        '.svg': 'image/svg+xml',
        '.txt': 'text/plain',
        '.xml': 'text/xml'
    }
    return content_types.get(ext, 'application/octet-stream')

def sanitize_variable_name(filename):
    """Convert filename to a valid C++ variable name."""
    # Remove extension and get full filename with extension for uniqueness
    name = Path(filename).name
    # Replace dots and invalid characters with underscores
    sanitized = ''.join(c if c.isalnum() else '_' for c in name)
    # Ensure it doesn't start with a number
    if sanitized and sanitized[0].isdigit():
        sanitized = 'file_' + sanitized
    return sanitized or 'unnamed_file'

def generate_header_file(file_path, content, is_binary=False):
    """Generate a C++ header file for embedded content."""
    filename = os.path.basename(file_path)
    var_name = sanitize_variable_name(filename)
    content_type = get_content_type(filename)
    
    # Generate checksum for integrity verification
    content_hash = hashlib.md5(content if isinstance(content, bytes) else content.encode()).hexdigest()[:8]
    
    header_content = f'''// Auto-generated embedded file: {filename}
// Generated by embed_webfiles.py - DO NOT MODIFY MANUALLY
// Content-Type: {content_type}
// File size: {len(content)} bytes
// Checksum: {content_hash}

#ifndef EMBEDDED_{var_name.upper()}_H
#define EMBEDDED_{var_name.upper()}_H

#include <Arduino.h>

'''
    
    if is_binary:
        # For binary files, embed as byte array
        if isinstance(content, str):
            content = content.encode('utf-8')
        
        header_content += f'''// Binary content stored in PROGMEM
const uint8_t embedded_{var_name}_data[] PROGMEM = {{
'''
        
        # Write bytes in rows of 16
        for i in range(0, len(content), 16):
            row = content[i:i+16]
            hex_values = ', '.join(f'0x{b:02X}' for b in row)
            header_content += f'    {hex_values}'
            if i + 16 < len(content):
                header_content += ','
            header_content += '\n'
        
        header_content += f'''}};

const size_t embedded_{var_name}_size = {len(content)};
const char embedded_{var_name}_content_type[] = "{content_type}";
const char embedded_{var_name}_filename[] = "{filename}";
const char embedded_{var_name}_checksum[] = "{content_hash}";

'''
    else:
        # For text files, use binary embedding for large files or files with problematic content
        if isinstance(content, str):
            content_bytes = content.encode('utf-8')
        else:
            content_bytes = content
        
        # For large files or JavaScript/CSS, always use binary embedding to avoid rawliteral issues
        if len(content_bytes) > 10000 or filename.endswith(('.js', '.css')):
            header_content += f'''// Large text content stored in PROGMEM as binary
const uint8_t embedded_{var_name}_data[] PROGMEM = {{
'''
            
            # Write bytes in rows of 16
            for i in range(0, len(content_bytes), 16):
                row = content_bytes[i:i+16]
                hex_values = ', '.join(f'0x{b:02X}' for b in row)
                header_content += f'    {hex_values}'
                if i + 16 < len(content_bytes):
                    header_content += ','
                header_content += '\n'
            
            header_content += f'''}};

const size_t embedded_{var_name}_size = {len(content_bytes)};
const char embedded_{var_name}_content_type[] = "{content_type}";
const char embedded_{var_name}_filename[] = "{filename}";
const char embedded_{var_name}_checksum[] = "{content_hash}";

'''
        else:
            # For small text files, use rawliteral
            if isinstance(content, bytes):
                content = content.decode('utf-8', errors='replace')
            
            header_content += f'''// Text content stored in PROGMEM
const char embedded_{var_name}_data[] PROGMEM = R"rawliteral({content})rawliteral";

const size_t embedded_{var_name}_size = {len(content)};
const char embedded_{var_name}_content_type[] = "{content_type}";
const char embedded_{var_name}_filename[] = "{filename}";
const char embedded_{var_name}_checksum[] = "{content_hash}";

'''
    
    header_content += f'''#endif // EMBEDDED_{var_name.upper()}_H
'''
    
    return header_content, var_name

def generate_registry_file(embedded_files):
    """Generate a registry file that lists all embedded files."""
    registry_content = '''// Auto-generated embedded files registry
// Generated by embed_webfiles.py - DO NOT MODIFY MANUALLY

#ifndef EMBEDDED_FILES_REGISTRY_H
#define EMBEDDED_FILES_REGISTRY_H

#include <Arduino.h>

'''
    
    # Include all generated headers
    for var_name, is_binary in embedded_files:
        registry_content += f'#include "embedded_{var_name}.h"\n'
    
    registry_content += '''
// Structure to hold embedded file information
struct EmbeddedFile {
    const char* filename;
    const char* content_type;
    const uint8_t* data;
    size_t size;
    const char* checksum;
    bool is_binary;
};

// Registry of all embedded files
const EmbeddedFile embedded_files[] = {
'''
    
    for var_name, is_binary_embedded in embedded_files:
        registry_content += f'''    {{
        embedded_{var_name}_filename,
        embedded_{var_name}_content_type,
        (const uint8_t*)embedded_{var_name}_data,
        embedded_{var_name}_size,
        embedded_{var_name}_checksum,
        {str(is_binary_embedded).lower()}
    }},
'''
    
    registry_content += '''};

const size_t embedded_files_count = sizeof(embedded_files) / sizeof(embedded_files[0]);

// Helper function to find an embedded file by path
const EmbeddedFile* findEmbeddedFile(const char* path);

#endif // EMBEDDED_FILES_REGISTRY_H
'''
    
    return registry_content

def generate_registry_cpp(embedded_files):
    """Generate the implementation file for the registry."""
    cpp_content = '''// Auto-generated embedded files registry implementation
// Generated by embed_webfiles.py - DO NOT MODIFY MANUALLY

#include "embedded_files_registry.h"
#include <string.h>

const EmbeddedFile* findEmbeddedFile(const char* path) {
    // Remove leading slash if present
    if (path[0] == '/') {
        path++;
    }
    
    for (size_t i = 0; i < embedded_files_count; i++) {
        if (strcmp(embedded_files[i].filename, path) == 0) {
            return &embedded_files[i];
        }
    }
    
    return nullptr;
}
'''
    
    return cpp_content

def main():
    """Main function to embed all files from upload directory."""
    # Get paths
    workspace_root = os.path.dirname(os.path.abspath(__file__))
    upload_dir = os.path.join(workspace_root, 'upload')
    generated_dir = os.path.join(workspace_root, 'src', 'generated')
    
    print("Embedding Web Files for DPV Control")
    print(f"Source directory: {upload_dir}")
    print(f"Output directory: {generated_dir}")
    
    # Check if upload directory exists
    if not os.path.exists(upload_dir):
        print(f"⚠️  Upload directory not found: {upload_dir}")
        print("   Creating upload directory...")
        os.makedirs(upload_dir, exist_ok=True)
        print("   Please move your web files from 'data/' to 'upload/' directory")
        return 0
    
    # Create generated directory
    os.makedirs(generated_dir, exist_ok=True)
    
    # Clean old generated files
    for old_file in os.listdir(generated_dir):
        if old_file.startswith('embedded_') and old_file.endswith('.h'):
            os.remove(os.path.join(generated_dir, old_file))
    
    embedded_files = []
    total_size = 0
    
    # Process all files in upload directory
    for root, dirs, files in os.walk(upload_dir):
        for filename in files:
            file_path = os.path.join(root, filename)
            relative_path = os.path.relpath(file_path, upload_dir)
            
            print(f"📄 Processing: {relative_path}")
            
            # Determine if file is binary
            is_binary = False
            content_type = get_content_type(filename)
            if content_type.startswith('image/') or filename.endswith(('.bin', '.zip', '.gz')):
                is_binary = True
            
            try:
                # Always read files as binary first to avoid encoding issues
                with open(file_path, 'rb') as f:
                    content_bytes = f.read()
                
                # For text files, try to decode to UTF-8, but keep binary as fallback
                if not is_binary:
                    try:
                        content = content_bytes.decode('utf-8')
                    except UnicodeDecodeError:
                        # If decoding fails, treat as binary
                        content = content_bytes
                        is_binary = True
                        print(f"   ⚠️  File {filename} contains non-UTF-8 content, treating as binary")
                else:
                    content = content_bytes
                
                # Determine if we'll use binary embedding (large files or JS/CSS)
                content_size = len(content) if isinstance(content, (str, bytes)) else 0
                will_use_binary = is_binary or content_size > 10000 or filename.endswith(('.js', '.css'))
                
                # Generate header file
                header_content, var_name = generate_header_file(relative_path, content, is_binary)
                
                # Write header file
                header_filename = f'embedded_{var_name}.h'
                header_path = os.path.join(generated_dir, header_filename)
                
                with open(header_path, 'w', encoding='utf-8') as f:
                    f.write(header_content)
                
                embedded_files.append((var_name, will_use_binary))
                file_size = len(content) if isinstance(content, (bytes, str)) else 0
                total_size += file_size
                
                print(f"   ✓ Generated: {header_filename} ({file_size} bytes)")
                
            except Exception as e:
                print(f"   ❌ Error processing {filename}: {e}")
                continue
    
    if embedded_files:
        # Generate registry files
        registry_header = generate_registry_file(embedded_files)
        registry_cpp = generate_registry_cpp(embedded_files)
        
        # Write registry files
        with open(os.path.join(generated_dir, 'embedded_files_registry.h'), 'w', encoding='utf-8') as f:
            f.write(registry_header)
        
        with open(os.path.join(generated_dir, 'embedded_files_registry.cpp'), 'w', encoding='utf-8') as f:
            f.write(registry_cpp)
        
        print(f"\n✅ Successfully embedded {len(embedded_files)} files")
        print(f"📊 Total embedded size: {total_size:,} bytes ({total_size/1024:.1f} KB)")
        print(f"📝 Generated files in: {generated_dir}")
        print("   - embedded_files_registry.h")
        print("   - embedded_files_registry.cpp")
        for var_name, is_binary in embedded_files:
            embed_type = "binary" if is_binary else "text"
            print(f"   - embedded_{var_name}.h ({embed_type})")
    else:
        print("⚠️  No files found to embed")
    
    return 0

if __name__ == "__main__":
    sys.exit(main()) 