name: CI

on:
  push:
    branches:
      - production_repo
  pull_request:

jobs:
  arduino-compile:
    name: Compile Arduino Sketches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Arduino sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32dev
          platforms: |
            - esp32:esp32
          sketch-paths: |
            - DPVController


