# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Lint Code Base

on:
  push:
    branches: [ "production_repo" ]
    paths:
      - 'src/**'
      - 'platformio.ini'
      - 'data/**'
      - '.github/workflows/**'
      - '!**/*.md'
      - '!**/*.png'
      - '!**/*.jpg'
      - '!**/*.jpeg'
  pull_request:
    branches: [ "production_repo" ]
    paths:
      - 'src/**'
      - 'platformio.ini'
      - 'data/**'
      - '.github/workflows/**'
      - '!**/*.md'
      - '!**/*.png'
      - '!**/*.jpg'
      - '!**/*.jpeg'
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          LOG_LEVEL: DEBUG        # Enable detailed logging
          VERBOSE: true           # Show detailed information for each linter run
          VALIDATE_CPP: true
          VALIDATE_CPP_CPPLINT: true
          VALIDATE_CPP_CPPCHECK: false
          VALIDATE_CPP_CLANG_FORMAT: false
          VALIDATE_CPP_CLANG_TIDY: false
          VALIDATE_CPP_CPPLINT_FILTER_REGEX: ".*\\.(cpp|h)$"
          VALIDATE_CPP_CPPLINT_OPTIONS: "--filter=-legal/copyright,-build/include_order,-build/include_what_you_use,-build/namespaces,-readability/todo,-runtime/references,-whitespace/line_length,-build/header_guard,-readability/casting,-runtime/int,-build/include_subdir,-whitespace/comments,-runtime/threadsafe_fn,-whitespace/parens,-whitespace/blank_line --linelength=120"
